stages:
  scrape-properties:
    cmd: scrape-properties dumped_data/2025-10-18T18:06:41+09:00/東京都.zip --output-filename
      dumped_data/2025-10-18T18:06:41+09:00/東京都.pickle --output-format pickle --jobs 3
    deps:
    - ../libs/otokuna
    - dumped_data/2025-10-18T18:06:41+09:00/東京都.zip
    outs:
    - dumped_data/2025-10-18T18:06:41+09:00/東京都.pickle
  train:
    cmd: ./train.py dumped_data/2025-10-18T18:06:41+09:00/東京都.pickle models/regressor
    deps:
    - ../libs/otokuna
    - dumped_data/2025-10-18T18:06:41+09:00/東京都.pickle
    - train.py
    outs:
    - models/regressor.cbm
    - models/regressor.onnx
    metrics:
    - metrics.json:
        cache: false
  check-onnx:
    cmd: ./check_onnx.py dumped_data/2025-10-18T18:06:41+09:00/東京都.pickle models/regressor.onnx models/regressor.cbm
    deps:
    - check_onnx.py
    - dumped_data/2025-10-18T18:06:41+09:00/東京都.pickle
    - models/regressor.cbm
    - models/regressor.onnx
    metrics:
    - check_onnx.json:
        cache: false
